version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      - redis
    env_file:
      - web-variables.env
  redis:
    image: "redis:alpine"
    volumes: 
      - redis-data:/data
  prometheus:
    image: "prom/prometheus"
volumes:
  redis-data:
    driver: local
    driver_opts:
      device: ./redis-vol