version: "3"
services:
  web:
    container_name: "${APP_NAME}-web"
    build: .
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WEB_PORT}/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      - redis
    env_file:
      - web-variables.env
  redis:
    container_name: "${APP_NAME}-redis"
    image: "redis/redis-stack:latest"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 1s
      retries: 5
      start_period: 5s
    env_file:
      - redis-variables.env
    volumes: 
      - ./redis-vol:/data
  prometheus:
    container_name: "${APP_NAME}-prometheus"
    image: "prom/prometheus"
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "localhost:9090/-/healthy"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./prometheus-vol:/etc/prometheus